import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اختر اللغة",
          "2": "اختر المنتج الخاص بك",
          "3":
              "ابحث واختر المنتجات التي تعجبك \n من مختلف العلامات التجارية. استكشف \n العلامات التجارية التي تعجبك وقم بتقديم الطلبات.",
          "4": "قم بالدفع",
          "5":
              "قم بإجراء الدفع عبر الإنترنت باستخدام الخدمات المصرفية عبر الإنترنت أو أي طرق دفع UPI يمكنك القيام بها. يتوفر أيضًا الدفع نقدًا عند التسليم.",
          "6": "احصل على طلبك في الوقت المحدد",
          "7":
              "نحن نقدم التسليم السريع قدر الإمكان. احصل على طلباتك يتم تسليمها في الوقت المحدد ويتم تسليمها بشكل آمن.",
          "8": "متابعه",
          "9": "تسجيل الدخول",
          "10": "اهلا بك",
          "11":
              "يمكنك تسجيل الدخول من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "12": "ادخل البريد الالكتروني",
          "13": "ادخل كلمة المرور",
          "14": "هل نسيت كلمة المرور",
          "15": "تسجيل الدخول",
          "16": "ليس لديك حساب ? ",
          "17": "انشاء حساب",
          "18": "البريد الالكتروني",
          "19": "كلمة المرور",
          "20": "اسم المستخدم",
          "21": "رقم الهاتف",
          "22": "ادخل رقم الهاتف",
          "23": "ادخل اسم المستخدم",
          "24":
              "انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
          "25": " لديك حساب ? ",
          "26": "تسجيل الدخول",
          "27": "فحص البريد الالكتروني",
          "28": "تم انشاء الحساب بنجاح",
          "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
          "30": "فحص",
          "31": "الذهاب لتسجيل الدخول",
          "32": "نجاح",
          "33": "حفظ",
          "34": "الرجاء ادخال كلمة المرور الجديدة",
          "35": "الكلمة الجديدة",
          "36": "تم اعادة تعيين كلمة المرور بنجاح",
          "37": "تهانينا",
          "38": "تم التسجيل بنجاح",
          "39": "استعاده كلمه المرور",

          "home": "الرئيسية",
          "profile": "الحساب",
          "categories": "الفئات",
          "shopcategories": "تسوق حسب الفئات",
          "favorite": "المفضلة",
          "cart": "السلة",
          "new arrived": "جديدنا ",
          "sale": "تخفيضات",
          "best seller": "الأكثر مبيعًا",
          "add to cart": "أضف إلى السلة",
          "explore more": "استكشف المزيد",
          "perfumes": "العطور",
          "frenchperfumes": "عطور فرنسيه",
          "skincare": "العناية بالبشرة",
          "hairprfume": "معطر الشعر",
          "makeup": "مستحضرات التجميل",
          "all products": "كل المنتجات",
          "load more": "تحميل المزيد",
          "addresses": "العناوين",
          "languages": "اللغات",
          "about": "حول التطبيق ",
          "log out": "تسجيل الخروج",
          "fullname": "الاسم بالكامل",
          "first name": "الاسم الاول",
          "last name": "الاسم الاخير",
          "name": "الاسم",
          "company": "الشركة",
          "address 1": "العنوان ١",
          "address 2": "العنوان ٢",
          "city": "المدينة",
          "country": "الدولة",
          "zone": "المحافظه/الولايه",
          "delete": "حذف",
          "edit": "تعديل",
          "confirm": "تأكيد",
          "continue": "المتابعه",
          "product details": "تفاصيل المنتج",
          "details": "التفاصيل",
          "opinion": "اراء العملاء",
          "addcomment": "اضف تعليق",
          "rate": "التقييم",
          "you may also like": "قد تعجبك أيضًا",
          "category details": "تفاصيل الفئة",
          "loading": "جار التحميل",
          "there are no products on sale": "لا توجد منتجات في التخفيضات",
          "empty": "فارغ",
          "no items in the favorites": "لا توجد عناصر في المفضلة",
          "no items in the cart": "لا توجد عناصر في سلتك",
          "sign in": "تسجيل الدخول",
          "register": "التسجيل",
          "you are just a visitor? continue as": "أنت زائر فقط؟ تابع كـ",
          "guest": "ضيف",
          "email address": "البريد الإلكتروني",
          "password": "كلمة المرور",
          "newpassword": "كلمة المرور الجديده",
          "login": "تسجيل الدخول",
          "new here?": "جديد هنا؟",
          "sign up": "التسجيل",
          'forgetpass': "استعاده كلمه المرور",
          "enter first name": "أدخل الاسم الأول",
          "enter last name": "أدخل الاسم الأخير",
          "phone number": "رقم الهاتف",
          "confirm password": "تأكيد كلمة المرور",
          "already user?": "مستخدم بالفعل؟",
          "registration failed": "فشل التسجيل",
          "copyright": "متجر ماركات © جميع الحقوق محفوظة ٢٠٢٣",
          "you are not a registered user": "الرجاء التسجيل / تسجيل الدخول",
          "only for registered users": "فقط للمستخدمين المسجلين،",
          "added successfully": "تمت الإضافة بنجاح",
          "removed successfully": "تم الإزالة بنجاح",
          "Suggested": "اللغات المتاحة",
          "english": "الإنجليزية 🇺🇸",
          "arabic": "العربية 🇰🇼",
          "welcome again": "مرحباً مجدداً",
          "products": "المنتجات",
          "already have an account?": "هل لديك حساب بالفعل ؟",
          "you don't havean account": "ليس لديك حساب ",
          "register now": "إنضم إلينا الآن",
          "all brands": "جميع العلامات التجارية",
          "search": "البحث ",
          "goToCheckout": "ملخص الطلب",
          "check": "تحقق",
          "delivery": "توصيل",
          "est total": "التقدير الإجمالي",
          "save": "حفظ",
          "users": "المستخدمين",
          "orders": "الطلبات",
          "checkout": "الدفع",
          "pricewithouttax": "السعر بدون ضريبه",
          "shipping address": "عنوان التوصيل",
          "add shipping address": "إضافة عنوان",
          "payment method": "طريقة الدفع",
          "shipping method": "طريقه الشحن",
          "total": "الإجمالي",
          "subtotal": "الاجمالي الفرعي",
          "free": "مجاني",
          "select payment method": "اختر وسيلة الدفع",
          "place order": "تأكيد الطلب",
          "pay online": "الدفع اونلاين",
          "cash on delivery": "الدفع عند الاستلام",
          "no selected address": "من فضلك إختر عنوان",
          "no selected payment method": "لم تختر طريقة للدفع",
          "add this address": "إضافة هذا العنوان",
          "editprofile": "تحرير معلومات حسابي",
          "editpassword": "تغيير كلمه المرور",
          "editadress": "تعديل العناوين",
          "editfavourits": "تعديل الرغبات",
          "profileinfo": "معلوماتك الشخصيه",
          "back": "رجوع",
          "postalcode": "الرقم البريدي",
          "myorders": "طلباتي",
          "logout": "تسجيل الخروج",
          "ourchoose": "مختاراتنا",
          "orderdone": "تم الطلب بنجاح يمكنك تتبع ,رقم الطلب ",

          "fe1title": "توصيل مجاني",
          "fe2title": "استرجاع خلال 15 يومًا",
          "fe3title": "دفع آمن",
          "fe4title": "دعم 24/7",
          "fe1stitle": "احصل على توصيل مجاني عند الشراء بقيمة 250 جنيه واكثر",
          "fe2stitle": "يمكنك استرجاع المنتجات التي قمت بشرائها خلال ١٥ يومًا",
          "fe3stitle": "دفع 100% آمن",
          "fe4stitle": "خدمة عملاء مميزة يمكنك التواصل معنا في اي وقت",
          //For Home Screen Featers

          "hfe1title": "ضمان أفضل الأسعار",
          "hfe2title": "توصيل مجاني",
          "hfe3title": "استرجاع المنتج",
          "hfe4title": "خدمة العملاء",
          "hfe1stitle": "ضمان أفضل الأسعار",
          "hfe2stitle": "احصل على توصيل مجاني عند الشراء بقيمة 250 جنيه واكثر",
          "hfe3stitle": "يمكنك استرجاع المنتجات التي قمت بشرائها خلال ١٥ يوم",
          "hfe4stitle": "خدمة عملاء مميزة يمكنك التواصل معنا في اي وقت",
          //
          "seeall": "مشاهده الكل",

          'le': 'جنيه',
          "allvendors": "جميع البائعين",

          'nodata': "لا يوجد نتائج",
          'avaliable': "متوفر",
          'unavaliable': "غير متوفر",
          'shipping': "تكلفه الشحن",
          "shipto": "شحن الى",
          'joinus': "انضم الينا ك بائع",
          "entervenorname": "ادخل الاسم التجاري",
          "vendorname": "الاسم التجاري",
          "productsmangment": "اداره المنتجات",
          "Enter as user": "الدخول كمستخدم",
          'add': "اضافه",
          "pn": "اسم المنتج",
          "pp": "سعر المنتج",
          "pq": "الكميه المتاحه",
          "pd": "الوصف",
        },
        "en": {
          "1": "Choose Language",
          "2": "Choose Your Product",
          "3":
              "Search and choose the products you like from various brands.Explore the brands you like and place the orders.",
          "4": "Make Payment",
          "5":
              "Make Online Payment using net banking or any UPI payment methods you can .Cash on Delivery is also available.",
          "6": "Get Your order on time",
          "7":
              "We Provide the fast delivery as possible. Get your Orders delivered on time and get it delivered safe.",
          "8": "Continue",
          "9": "Sign In",
          "10": "Welcome Back",
          "11":
              "Sign In Your Email And Password Or  Continue With Social Media",
          "12": "Enter Your Email",
          "13": "Enter Your Password",
          "14": "Forget Password",
          "15": "Sign In",
          "16": "Dont Have An Account ? ",
          "17": "Sign Up",
          "18": "Email",
          "19": "Password",
          "20": "Username",
          "21": "Phone",
          "22": "Enter Your Phone",
          "23": "Enter Your Username",
          "24":
              "Sign Up With Your Email And Password OR Continue With Social Media",
          "25": " have an account ? ",
          "26": "SignIn",
          "27": "Check Email",
          "28": "Account successfully created",
          "29": "please Enter Your Email Address To Recive A verification code",
          "30": "check",
          "31": "Go To Login",
          "32": "Success",
          "33": "save",
          "34": "Please Enter new Password",
          "35": "New Password",
          "36": "Password has been reset successfully",
          "37": "congratulations",
          "38": "successfully registered",
          "39": "Reset Password",
          "save": "Save",
          "users": "Users",
          "orders": "Orders",
          "home": "Home",
          "profile": "Profile",
          "categories": "Categories",
          "shopcategories": "Shopping by categories",
          "favorite": "Favorite",
          "cart": "Cart",
          "new arrived": "NEW ARRIVED",
          "sale": "SALE",
          "best seller": "BEST SELLER",
          "add to cart": "Add to Cart",
          "explore more": "EXPLORE MORE",
          "perfumes": "PERFUMES",
          "frenchperfumes": "FRENCH PERFUMES",
          "skincare": "Skin Care",
          "hairprfume": "Hair perfume",
          "makeup": "MAKEUP",
          "all products": "ALL PRODUCTS",
          "load more": "LOAD MORE",
          "addresses": "Addresses",
          "languages": "Languages",
          "about": "About",
          "log out": "Log Out",
          "fullname": "Full Name",
          "first name": "First Name",
          "last name": "Last Name",
          "name": "Name",
          "company": "Company",
          "address 1": "Address 1",
          "address 2": "Address 2",
          "city": "City",
          "country": "Country",
          "zone": "Region/state",
          "delete": "Delete",
          "edit": "Edit",
          "confirm": "Confirm",
          "continue": "Continue",
          "product details": "Product Details",
          "details": "Description",
          "opinion": "ٌReviews",
          "rate": "Rate",
          "addcomment": "Add Comment",
          "you may also like": "YOU MAY ALSO LIKE",
          "category details": "Category Details",
          "loading": "Loading",
          "there are no products on sale": "There are no products on sale",
          "empty": "Empty",
          "no items in the favorites": "No items in the favorites",
          "no items in the cart": "No items in your cart",
          "sign in": "Sign In",
          "register": "Register",
          "you are just a visitor? continue as":
              "You are just a visitor? Continue as ",
          "guest": "Guest",
          "email address": "email address",
          "password": "password",
          "newpassword": "New password",
          "login": "Login",
          "new here?": "New here",
          "sign up": "Sign up",
          'forgetpass': "Restore Password",
          "enter first name": "Enter first name",
          "enter last name": "Enter Last Name",
          "phone number": "phone number",
          "confirm password": "Confirm password",
          "already user?": "Already user",
          "registration failed": "Registration failed",
          "copyright": "MARKAT STORE © All rights reserved 2023",
          "you are not registered user": "You are not registered user",
          "only for registered users":
              "Only for registered users, try again later",
          "added successfully": "Added Successfully",
          "removed successfully": "Removed Successfully",
          "sugguested": "Available languages",
          "english": "English 🇺🇸",
          "arabic": "Arabic 🇰🇼",
          "welcome again": "Welcome again",
          "products": "Prodcuts",
          "already have an account": "Already have an account?",
          "you don't havean account": "You don't have an account",
          "register now": "Register Now!",
          "all brands": "All Brands",
          "search": "Search",
          "goToCheckout": "Order Summary",
          "check": "Check",
          "delivery": "Delivery",
          "subtotal": "Sub-Total",
          "shipto": "Ship To",
          "est total": "EST. TOTAL",
          "checkout": "Checkout",
          "shipping address": "Shipping Address",
          "shipping method": "Shipping Method",
          "add shipping address": "Add shipping address",
          "payment method": "Payment Method",
          "total": "Total",
          "free": "Free",
          "pricewithouttax": "Price without tax",
          "select payment method": "Select payment method",
          "placer order": "Place Order",
          "pay online": "Pay Online",
          "cash on delivery": "Cash On Delivery",
          "no selected address": "Please select an address",
          "no selected payment method": "No selected payment method",
          "add this address": "Add this address",
          "editprofile": "Edit Profile",
          "editpassword": "Edit Password",
          "editadress": "Edit Address",
          "editfavourits": "Edit Favourits",
          "profileinfo": "Your Personal Details",
          "back": "Back",
          "postalcode": "Postal Code",
          "myorders": "My Orders",
          "logout": "Sign Out",
          "ourchoose": "Our Picks",
          "fe1title": "Free Delivery",
          "fe2title": "15 Days Return",
          "fe3title": "Secure Payment",
          "fe4title": "24/7 Support",
          "fe1stitle": "Get free delivery on purchases of 250 LE or more",
          "fe2stitle":
              "You can return the products you have purchased within 15 days",
          "fe3stitle": "100% secure payment",
          "fe4stitle":
              "Distinguished customer service, you can contact us at any time",
          //For Home Screen Featers

          "hfe1title": "Best price guarantee",
          "hfe2title": "Free delivery ",
          "hfe3title": "Hassle-Free",
          "hfe4title": "customer service",
          "hfe1stitle": "We are distinguished by competitive and low prices",
          "hfe2stitle": "Get free delivery on purchases of 250 LE or more",
          "hfe3stitle":
              "You can return the products you have purchased within 15 days",
          "hfe4stitle":
              "Distinguished customer service, you can contact us at any time",
          "orderdone":
              "The order was completed successfully. You can track the order number ",
          "seeall": "See All",

          "le": "LE",
          "allvendors": "All Vendors",
          "nodata": "No Results",
          'avaliable': "Available",
          'unavaliable': 'Unavailable',
          'shipping': "Shipping cost",
          "joinus": "Join us as Seller..",
          "entervenorname": "Enter Commercial Name",
          "vendorname": "Commercial Name",
          "productsmangment": "Products Mangment",
          "add": 'Add',
          "pn": "Product Name",
          "pp": "Product Price",
          "pq": "Product Quntity",
          "pd": "Product Description",
        }
      };
}
